sonar.projectKey=BookBase
sonar.projectName=BookBase
sonar.qualitygate.wait=true

sonar.sources=src
sonar.exclusions=**/test/**,**/node_modules/**

# coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
